services:
  nest:
    image: ghcr.io/rezi-labs/rezi-nest
    env_file:
      - path: .env
        required: false
    environment:
      SERVER_PORT: 9998
      API_KEY: "very-secure"
    ports:
      - "9998:9998"